Zahlenraten Main Feature
kittyevi/ZahlenratenPython pull request #1
Opened 2022-11-21 09:05 UTC by AlenoJankowsky

PR: #1

2022-11-21 09:23 UTC, stefanluth requested changes

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +import sys
Unused import :)

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +
Put this in a function as well :)

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +main_game()
Add a `if __name__ == '__main__'` here :)

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +            try:
Indentation seems off :D

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +                if (guess < 1 or guess > 20):
```suggestion
                if 1 > guess > 20:
```

This _should_ work, but test it :D

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +                continue
This whole function is kind of over-engineered. Try to simplify :)

2022-11-21 09:23 UTC, stefanluth commented on main.py
> +        while not test_input(random_number, guess, amount_of_tries):
The function name does not suggest a boolean return. Maybe `is_valid_input` :D

2022-11-21 09:56 UTC, DevBastiS requested changes

2022-11-21 09:56 UTC, DevBastiS commented on main.py
> +            if (1 > guess > 20):
1 and 20 are magic numbers here, move them to constants with speaking name.

2022-11-21 09:56 UTC, DevBastiS commented on main.py
> +                print("Eingabe unzulaessig. Bitte geben Sie erneut eine Zahl zwischen 1 und 20 ein:  ", end="")
Is this if case necessary?

2022-11-21 10:07 UTC, kittyevi commented on main.py
> +                if (guess < 1 or guess > 20):
Doesn't work unfortunately

2022-11-21 10:31 UTC, stefanluth requested changes

2022-11-21 10:31 UTC, stefanluth commented on main.py
> +max_random_number_limit = 19
```suggestion
MIN_NUM = 5
MAX_NUM = 19
```

Constants are UPPER_CASE :)

2022-11-21 10:31 UTC, stefanluth commented on main.py
> +            return guess
```suggestion
        try: 
            guess = int(input(f"Bitte geben Sie eine Zahl zwischen {min_random_number_limit} und {max_random_number_limit} ein: "))
            if (min_random_number_limit > guess or guess > max_random_number_limit):
                raise ValueError
            return guess
        except ValueError:
            print("Eingabe unzulaessig. ", end="")
            continue
```

2022-11-22 07:57 UTC, Jeremy-Hill-02 requested changes

2022-11-22 07:57 UTC, Jeremy-Hill-02 commented on main.py
> +                raise ValueError
```suggestion
                raise ValueError
                
```

2022-11-22 07:57 UTC, Jeremy-Hill-02 commented on main.py
> +import random
since you only need the randint func, only import this func

2022-11-22 08:25 UTC, stefanluth approved these changes

2022-11-22 08:39 UTC, gazer42 approved these changes

2022-11-22 08:53 UTC, DevBastiS approved these changes

2022-11-22 08:58 UTC, merged